//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp20.API.DataAccess.Models
{
    using Params;
    using System;
    using System.Collections.Generic;

    public partial class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public Item() { }
        public Item(ItemParam itemparam)
        {
            this.Name = itemparam.Name;
            this.Price = itemparam.Price;
            this.Stock = itemparam.Stock;
            this.Supplier = itemparam.Supplier;
            this.CreateDate = DateTimeOffset.Now.LocalDateTime;
        }
        public void Update(ItemParam itemparam)
        {
            this.Name = itemparam.Name;
            this.Stock = itemparam.Stock;
            this.Price = itemparam.Price;
            this.Supplier = itemparam.Supplier;
            this.UpdateDate = DateTimeOffset.Now.LocalDateTime;
        }

    }
}
